### ISSUE TITLE
ERROR while running example code

### ISSUE THREAD

**Issue by saurabh502** [mgrankin/fast_tabnet#3]
When I am running example script provided here:
[](https://github.com/mgrankin/fast_tabnet)
on step, learn.lr_find() , I am getting bellow error:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-d81c6bd29d71> in <module>
----> 1 learn.lr_find()

/opt/conda/lib/python3.7/site-packages/fastai2/callback/schedule.py in lr_find(self, start_lr, end_lr, num_it, stop_div, show_plot, suggestions)
    226     n_epoch = num_it//len(self.dls.train) + 1
    227     cb=LRFinder(start_lr=start_lr, end_lr=end_lr, num_it=num_it, stop_div=stop_div)
--> 228     with self.no_logging(): self.fit(n_epoch, cbs=cb)
    229     if show_plot: self.recorder.plot_lr_find()
    230     if suggestions:

/opt/conda/lib/python3.7/site-packages/fastcore/utils.py in _f(*args, **kwargs)
    429         init_args.update(log)
    430         setattr(inst, 'init_args', init_args)
--> 431         return inst if to_return else f(*args, **kwargs)
    432     return _f
    433 

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    198                     try:
    199                         self.epoch=epoch;          self('begin_epoch')
--> 200                         self._do_epoch_train()
    201                         self._do_epoch_validate()
    202                     except CancelEpochException:   self('after_cancel_epoch')

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in _do_epoch_train(self)
    173         try:
    174             self.dl = self.dls.train;                        self('begin_train')
--> 175             self.all_batches()
    176         except CancelTrainException:                         self('after_cancel_train')
    177         finally:                                             self('after_train')

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in all_batches(self)
    151     def all_batches(self):
    152         self.n_iter = len(self.dl)
--> 153         for o in enumerate(self.dl): self.one_batch(*o)
    154 
    155     def one_batch(self, i, b):

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in one_batch(self, i, b)
    157         try:
    158             self._split(b);                                  self('begin_batch')
--> 159             self.pred = self.model(*self.xb);                self('after_pred')
    160             if len(self.yb) == 0: return
    161             self.loss = self.loss_func(self.pred, *self.yb); self('after_loss')

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/fast_tabnet/core.py in forward(self, x_cat, x_cont)
     32             x_cont = self.bn_cont(x_cont)
     33             x = torch.cat([x, x_cont], 1) if self.n_emb != 0 else x_cont
---> 34         x, _, _, _ = self.tab_net(x)
     35         if self.y_range is not None:
     36             x = (self.y_range[1]-self.y_range[0]) * torch.sigmoid(x) + self.y_range[0]

ValueError: not enough values to unpack (expected 4, got 2)`

**Comment by ncduy0303** [comment]
I'm also facing exactly the same error running that notebook on both Google Colab and Jupyter Notebook

**Comment by mgrankin** [comment]
I've uploaded an updated version to pip, try it, pls.

**Comment by ncduy0303** [comment]
> I've uploaded an updated version to pip, try it, pls.

Great, it works for me now. Thank you for the quick response!

**Comment by saurabh502** [comment]
on different data I am getting below error:
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-d81c6bd29d71> in <module>
----> 1 learn.lr_find()

/opt/conda/lib/python3.7/site-packages/fastai2/callback/schedule.py in lr_find(self, start_lr, end_lr, num_it, stop_div, show_plot, suggestions)
    226     n_epoch = num_it//len(self.dls.train) + 1
    227     cb=LRFinder(start_lr=start_lr, end_lr=end_lr, num_it=num_it, stop_div=stop_div)
--> 228     with self.no_logging(): self.fit(n_epoch, cbs=cb)
    229     if show_plot: self.recorder.plot_lr_find()
    230     if suggestions:

/opt/conda/lib/python3.7/site-packages/fastcore/utils.py in _f(*args, **kwargs)
    429         init_args.update(log)
    430         setattr(inst, 'init_args', init_args)
--> 431         return inst if to_return else f(*args, **kwargs)
    432     return _f
    433 

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    198                     try:
    199                         self.epoch=epoch;          self('begin_epoch')
--> 200                         self._do_epoch_train()
    201                         self._do_epoch_validate()
    202                     except CancelEpochException:   self('after_cancel_epoch')

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in _do_epoch_train(self)
    173         try:
    174             self.dl = self.dls.train;                        self('begin_train')
--> 175             self.all_batches()
    176         except CancelTrainException:                         self('after_cancel_train')
    177         finally:                                             self('after_train')

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in all_batches(self)
    151     def all_batches(self):
    152         self.n_iter = len(self.dl)
--> 153         for o in enumerate(self.dl): self.one_batch(*o)
    154 
    155     def one_batch(self, i, b):

/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in one_batch(self, i, b)
    157         try:
    158             self._split(b);                                  self('begin_batch')
--> 159             self.pred = self.model(*self.xb);                self('after_pred')
    160             if len(self.yb) == 0: return
    161             self.loss = self.loss_func(self.pred, *self.yb); self('after_loss')

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/fast_tabnet/core.py in forward(self, x_cat, x_cont)
     32             x_cont = self.bn_cont(x_cont)
     33             x = torch.cat([x, x_cont], 1) if self.n_emb != 0 else x_cont
---> 34         x, _ = self.tab_net(x)
     35         if self.y_range is not None:
     36             x = (self.y_range[1]-self.y_range[0]) * torch.sigmoid(x) + self.y_range[0]

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/pytorch_tabnet/tab_network.py in forward(self, x)
    130 
    131         for step in range(self.n_steps):
--> 132             M = self.att_transformers[step](prior, att)
    133             M_loss += torch.mean(torch.sum(torch.mul(M, torch.log(M+self.epsilon)),
    134                                            dim=1))

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/pytorch_tabnet/tab_network.py in forward(self, priors, processed_feat)
    290         x = self.bn(x)
    291         x = torch.mul(x, priors)
--> 292         x = self.sp_max(x)
    293         return x
    294 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/pytorch_tabnet/sparsemax.py in forward(self, input)
     89 
     90     def forward(self, input):
---> 91         return sparsemax(input, self.dim)
     92 
     93 

/opt/conda/lib/python3.7/site-packages/pytorch_tabnet/sparsemax.py in forward(ctx, input, dim)
     41         max_val, _ = input.max(dim=dim, keepdim=True)
     42         input -= max_val  # same numerical stability trick as for softmax
---> 43         tau, supp_size = SparsemaxFunction._threshold_and_support(input, dim=dim)
     44         output = torch.clamp(input - tau, min=0)
     45         ctx.save_for_backward(supp_size, output)

/opt/conda/lib/python3.7/site-packages/pytorch_tabnet/sparsemax.py in _threshold_and_support(input, dim)
     74 
     75         support_size = support.sum(dim=dim).unsqueeze(dim)
---> 76         tau = input_cumsum.gather(dim, support_size - 1)
     77         tau /= support_size.to(input.dtype)
     78         return tau, support_size

RuntimeError: index -1 is out of bounds for dimension 1 with size 221`

**Comment by mgrankin** [comment]
Can't reproduce the error. The notebook with samples is working ok?

**Comment by saurabh502** [comment]
yes sample is working fine, but not in my data

**Comment by alexanderwatanabe** [comment]
I have the same issue both with lr_find and fit_one_cycle:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-d81c6bd29d71> in <module>
----> 1 learn.lr_find()

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/callback/schedule.py in lr_find(self, start_lr, end_lr, num_it, stop_div, show_plot, suggestions)
    222     n_epoch = num_it//len(self.dls.train) + 1
    223     cb=LRFinder(start_lr=start_lr, end_lr=end_lr, num_it=num_it, stop_div=stop_div)
--> 224     with self.no_logging(): self.fit(n_epoch, cbs=cb)
    225     if show_plot: self.recorder.plot_lr_find()
    226     if suggestions:

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    203             self.opt.set_hypers(lr=self.lr if lr is None else lr)
    204             self.n_epoch = n_epoch
--> 205             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
    206 
    207     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    152 
    153     def _with_events(self, f, event_type, ex, final=noop):
--> 154         try:       self(f'before_{event_type}')       ;f()
    155         except ex: self(f'after_cancel_{event_type}')
    156         finally:   self(f'after_{event_type}')        ;final()

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _do_fit(self)
    194         for epoch in range(self.n_epoch):
    195             self.epoch=epoch
--> 196             self._with_events(self._do_epoch, 'epoch', CancelEpochException)
    197 
    198     def fit(self, n_epoch, lr=None, wd=None, cbs=None, reset_opt=False):

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    152 
    153     def _with_events(self, f, event_type, ex, final=noop):
--> 154         try:       self(f'before_{event_type}')       ;f()
    155         except ex: self(f'after_cancel_{event_type}')
    156         finally:   self(f'after_{event_type}')        ;final()

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _do_epoch(self)
    188 
    189     def _do_epoch(self):
--> 190         self._do_epoch_train()
    191         self._do_epoch_validate()
    192 

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _do_epoch_train(self)
    180     def _do_epoch_train(self):
    181         self.dl = self.dls.train
--> 182         self._with_events(self.all_batches, 'train', CancelTrainException)
    183 
    184     def _do_epoch_validate(self, ds_idx=1, dl=None):

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    152 
    153     def _with_events(self, f, event_type, ex, final=noop):
--> 154         try:       self(f'before_{event_type}')       ;f()
    155         except ex: self(f'after_cancel_{event_type}')
    156         finally:   self(f'after_{event_type}')        ;final()

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in all_batches(self)
    158     def all_batches(self):
    159         self.n_iter = len(self.dl)
--> 160         for o in enumerate(self.dl): self.one_batch(*o)
    161 
    162     def _do_one_batch(self):

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in one_batch(self, i, b)
    176         self.iter = i
    177         self._split(b)
--> 178         self._with_events(self._do_one_batch, 'batch', CancelBatchException)
    179 
    180     def _do_epoch_train(self):

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    152 
    153     def _with_events(self, f, event_type, ex, final=noop):
--> 154         try:       self(f'before_{event_type}')       ;f()
    155         except ex: self(f'after_cancel_{event_type}')
    156         finally:   self(f'after_{event_type}')        ;final()

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/fastai/learner.py in _do_one_batch(self)
    161 
    162     def _do_one_batch(self):
--> 163         self.pred = self.model(*self.xb)
    164         self('after_pred')
    165         if len(self.yb): self.loss = self.loss_func(self.pred, *self.yb)

~/dev/Practical-Deep-Learning-for-Coders-2.0/fast_tabnet/.venv-nix/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

<ipython-input-11-16f36b5dcdbe> in forward(self, x_cat, x_cont, att)
     22             x_cont = self.bn_cont(x_cont)
     23             x = torch.cat([x, x_cont], 1) if self.n_emb != 0 else x_cont
---> 24         x, m_loss, m_explain, masks = self.tab_net(x)
     25         if self.y_range is not None:
     26             x = (self.y_range[1]-self.y_range[0]) * torch.sigmoid(x) + self.y_range[0]

ValueError: not enough values to unpack (expected 4, got 2)
```

**Comment by mgrankin** [comment]
Hi, update the package.

**Comment by alexanderwatanabe** [comment]
thanks for the reply,
`fast_tabnet.__version__` returns:
`'0.2.0'`

**Comment by mgrankin** [comment]
Then it's weird. The code 
`
x, m_loss, m_explain, masks = self.tab_net(x)
`
is not longer in the package. It's now 
`
y, _ = self.tab_net(x)
`
