### ISSUE TITLE
Regressor function for fast_tabnet

### ISSUE THREAD

**Issue by zjgbz** [mgrankin/fast_tabnet#6]
Hi,

Thank you very much for building this library, and since my task is actually a regression problem, I am wondering if this fast_tabnet has any regressor function? And if so, could you provide some simple examples? Thank you very much.

Best regards,
Wu-Sheng

**Comment by mgrankin** [comment]
Hi,

Please, take a look at `Sarcos Robotics Arm Inverse Dynamics` sample in `01_examples.ipynb`

**Comment by zjgbz** [comment]
Thank you very much!
