### ISSUE TITLE
How to use fast_tabnet for a multi-label  classification task?

### ISSUE THREAD

**Issue by pankaj-kvhld** [mgrankin/fast_tabnet#9]
Thank you very much for creating this library. 

I couldn't figure out how exactly to solve a multi-label classification problem using it. Any tip will be very helpful.

Thank you very much.

**Comment by mgrankin** [comment]
Hello, 

It's probably better to google how to do that using fastai library (v2). Once done, you can try tabnet architecture to see if that would improve the result.

**Comment by mgrankin** [comment]
You can check their forum, it's welcoming and full of people who might help you https://forums.fast.ai

**Comment by pankaj-kvhld** [comment]
Thank you, I found my error.
